version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=comment
    ports:
      - "5432:5432"
  comments-service:
    image: comments-api
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://postgres:5432/comment
    ports:
      - "8087:8087"
    depends_on:
      - postgres
