language: java
jdk: oraclejdk8
install: true
script:
  - mvn clean package
  - docker build -t $DOCKER_USERNAME/$REPO:users-api -f user/Dockerfile user/
  - docker build -t $DOCKER_USERNAME/$REPO:videos-api -f video/Dockerfile video/
  - docker build -t $DOCKER_USERNAME/$REPO:demo-api -f demo/Dockerfile demo/
  - docker build -t $DOCKER_USERNAME/$REPO:config -f config/Dockerfile config/
  - docker build -t $DOCKER_USERNAME/$REPO:subscriptions-api -f subscription/Dockerfile subscription/
  - docker build -t $DOCKER_USERNAME/$REPO:ratings-api -f rating/Dockerfile rating/
  - docker build -t $DOCKER_USERNAME/$REPO:recommendations-api -f recommendation/Dockerfile recommendation/
  - docker build -t $DOCKER_USERNAME/$REPO:comments-api -f comment/Dockerfile comment/
  - docker build -t $DOCKER_USERNAME/$REPO:uploaders-api -f upload/Dockerfile upload/

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_USERNAME/$REPO:users-api
  - docker push $DOCKER_USERNAME/$REPO:videos-api
  - docker push $DOCKER_USERNAME/$REPO:demo-api
  - docker push $DOCKER_USERNAME/$REPO:config
  - docker push $DOCKER_USERNAME/$REPO:subscriptions-api
  - docker push $DOCKER_USERNAME/$REPO:ratings-api
  - docker push $DOCKER_USERNAME/$REPO:recommendations-api
  - docker push $DOCKER_USERNAME/$REPO:comments-api
  - docker push $DOCKER_USERNAME/$REPO:uploaders-api
