language: java
jdk: oraclejdk8
install: true
script:
  - mvn clean package
  - docker build -t users-api -f user/Dockerfile.txt user/
  - docker build -t videos-api -f video/Dockerfile.txt video/

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_USERNAME/streaming_app:users-api
  - docker push $DOCKER_USERNAME/streaming_app:videos-api