version: "3"
services:
  etcd:
    image: quay.io/coreos/etcd:latest
    restart: always
    ports:
      - "2379:2379"
    volumes:
      - /tmp/etcd-data:/etcd-data
    environment:
      - ETCD_NAME=my-etcd
      - ETCD_DATA_DIR=/etcd-data
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER=my-etcd=http://0.0.0.0:2380
      - ETCD_INITIAL_CLUSTER_TOKEN=my-etcd-token
      - ETCD_INITIAL_CLUSTER_STATE=new
      - ETCD_AUTO_COMPACTION_RETENTION=1
      - ETCD_CORS=*

  postgres-user:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user
    ports:
      - "5432:5432"

  postgres-video:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=video
    ports:
      - "5433:5432"

  postgres-subscription:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=subscription
    ports:
      - "5434:5432"

  user-service:
    build:
      context: user
      dockerfile: Dockerfile
    image: stashvala/streaming_app:users-api
    #image: users-api # used for local building
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://postgres-user:5432/user
      - KUMULUZEE_CONFIG_ETCD_HOSTS=http://etcd:2379
      - KUMULUZEE_DISCOVERY_ETCD_HOSTS=http://etcd:2379
    ports:
      - "8080:8080"
    depends_on:
      - postgres-user

  video-service:
    build:
      context: video
      dockerfile: Dockerfile
    image: stashvala/streaming_app:videos-api
    #image: videos-api # used for local building
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://postgres-video:5432/video
      - KUMULUZEE_CONFIG_ETCD_HOSTS=http://etcd:2379
      - KUMULUZEE_DISCOVERY_ETCD_HOSTS=http://etcd:2379
      - KUMULUZEE_SERVER_BASE-URL=http://video-service:8081
    ports:
      - "8082:8082"
    depends_on:
      - postgres-video

  demo-service:
      build:
        context: demo
        dockerfile: Dockerfile
      image: demo-api
      ports:
        - "8081:8081"

  config-service:
    build:
      context: config
      dockerfile: Dockerfile
    image: stashvala/streaming_app:config
    ports:
      - "8083:8083"

  subs-service:
    build:
      context: subscription
      dockerfile: Dockerfile
    image: stashvala/streaming_app:subscriptions-api
    ports:
      - "8084:8084"
    environment:
         - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://postgres-subscription:5432/subscription
         - KUMULUZEE_CONFIG_ETCD_HOSTS=http://etcd:2379
         - KUMULUZEE_DISCOVERY_ETCD_HOSTS=http://etcd:2379
    depends_on:
      - postgres-subscription

  postgres-rating:
      image: postgres:latest
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=rating
      ports:
        - "5435:5432"

  ratings-service:
      build:
        context: rating
        dockerfile: Dockerfile
      image: stashvala/streaming_app:ratings-api
      ports:
        - "8085:8085"
      environment:
           - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://postgres-rating:5432/rating
           - KUMULUZEE_CONFIG_ETCD_HOSTS=http://etcd:2379
           - KUMULUZEE_DISCOVERY_ETCD_HOSTS=http://etcd:2379
      depends_on:
        - postgres-rating

  recommendations-service:
    build:
      context: recommendation
      dockerfile: Dockerfile
    image: stashvala/streaming_app:recommendations-api
    ports:
      - "8086:8086"
    environment:
         - KUMULUZEE_CONFIG_ETCD_HOSTS=http://etcd:2379
         - KUMULUZEE_DISCOVERY_ETCD_HOSTS=http://etcd:2379

  postgres-comment:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=comment
    ports:
      - "5436:5432"

  comments-service:
    build:
      context: comment
      dockerfile: Dockerfile
    image: stashvala/streaming_app:comments-api
    ports:
      - "8087:8087"
    environment:
         - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://postgres-comment:5432/comment
         - KUMULUZEE_CONFIG_ETCD_HOSTS=http://etcd:2379
         - KUMULUZEE_DISCOVERY_ETCD_HOSTS=http://etcd:2379
    depends_on:
      - postgres-comment

  uploaders-service:
    build:
      context: uploader
      dockerfile: Dockerfile
    image: stashvala/streaming_app:uploaders-api
    ports:
      - "8088:8088"
    environment:
         - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://postgres-uploader:5432/uploader
         - KUMULUZEE_CONFIG_ETCD_HOSTS=http://etcd:2379
         - KUMULUZEE_DISCOVERY_ETCD_HOSTS=http://etcd:2379
    depends_on:
      - postgres-uploader

  postgres-uploader:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=uploader
    ports:
      - "5437:5432"
