kumuluzee:
  name: player-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8089
    http:
      port: 8089
  config:
    etcd:
      hosts: http://localhost:2379
  discovery:
    etcd:
      hosts: http://localhost:2379