version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rating
    ports:
      - "5432:5432"
  subs-service:
    image: ratings-api
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://postgres:5432/rating
    ports:
      - "8085:8085"
    depends_on:
      - postgres
