version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=subscription
    ports:
      - "5432:5432"
  subs-service:
    image: subscriptions-api
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://postgres:5432/subscription
    ports:
      - "8084:8084"
    depends_on:
      - postgres
