version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=video
    ports:
      - "5433:5432"
  video-service:
    image: videos-api:1.00
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://postgres:5432/video
    ports:
      - "8081:8081"
    depends_on:
      - postgres