version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=video
    ports:
      - "33333:5432"
  video-service:
    image: videos-api
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://172.17.0.1:33333/video
    ports:
      - "8080:8080"
    depends_on:
      - postgres