kumuluzee:
  name: video-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://*:8082
    http:
      port: 8082
  datasources:
    - jndi-name: jdbc/VideosDS
      connection-url: jdbc:postgresql://172.17.0.1:5433/videos
      username: postgres
      password: postgres
      max-pool-size: 20
  config:
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
    etcd:
      hosts: http://localhost:2379
    ttl: 20
    ping-interval: 15