kumuluzee:
  name: video-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  datasources:
    - jndi-name: jdbc/VideosDS
      connection-url: jdbc:postgresql://172.17.0.1:33334/videos
      username: postgres
      password: postgres
      max-pool-size: 20
  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://172.17.0.1:2379
  discovery:
    etcd:
      hosts: http://172.17.0.1:2379
    ttl: 30
    ping-interval: 5