kumuluzee:
  name: comments-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8087
    http:
      port: 8087
  datasources:
    - jndi-name: jdbc/CommentsDS
      connection-url: jdbc:postgresql://172.17.0.1:5432/comment
      username: postgres
      password: postgres
      max-pool-size: 20
  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/CommentsDS
  cors-filter:
    servlet:
      allow-origin: "*"
  metrics:
      web-instrumentation:
        - name: comments-endpoint
          url-pattern: /v1/comments/*
  config:
    etcd:
        hosts: http://192.168.99.100:2379
  discovery:
    etcd:
      hosts: http://localhost:2379
    ttl: 20
    ping-interval: 15

rest-properties:
  healthy: true