apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres-user-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-user
    spec:
      containers:
      #- image: postgres:latest
      - image: centos/postgresql-94-centos7
        name: postgres-user
        env:
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_DB
            value: user

        ports:
        - containerPort: 5432
          name: server
          protocol: TCP


---

apiVersion: v1
kind: Service
metadata:
  name: postgres-user
spec:
  type: ClusterIP
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres-user
