apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres-video-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-video
    spec:
      containers:
      - image: postgres:latest
        name: postgres-video
        env:
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_DB
            value: video

        ports:
        - containerPort: 5432
          name: server
          protocol: TCP