apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres-user-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-user
    spec:
      containers:
      - image: postgres:latest
        name: postgres-user
        env:
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_DB
            value: user

        ports:
        - containerPort: 5432
          name: server
          protocol: TCP