apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: recommendation-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: recommendation
    spec:
      containers:
      - image: stashvala/streaming_app:recommendations-api
        imagePullPolicy: Always
        name: kubernetes-recommendation
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: orangeboss
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
        ports:
        - containerPort: 8086
          name: server
          protocol: TCP
