apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: uploader-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: uploader
    spec:
      containers:
      - image: stashvala/streaming_app:uploaders-api
        imagePullPolicy: Always
        name: kubernetes-uploader
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: private-coreos
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-uploader:5432/uploader
          - name: KUMULUZEE_DATASOURCES0_PASSWORD
            value: postgres
          - name: KUMULUZEE_HEALTH_CHECKS_DATASOURCEHEALTHCHECK_CONNECTIONURL
            value: jdbc:postgresql://postgres-uploader:5432/uploader
        livenessProbe:
          httpGet:
            path: /health
            port: server
          initialDelaySeconds: 10
          periodSeconds: 3
        ports:
        - containerPort: 8088
          name: server
          protocol: TCP
