apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - image: docker.io/stashvala/streaming_app:users-api
        imagePullPolicy: Always
        name: user
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: googlecloud
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-user:5432/user
          - name: KUMULUZEE_DATASOURCES0_PASSWORD
            value: postgres
        #livenessProbe:
        #  httpGet:
        #    path: /health
        #    port: server
        #  initialDelaySeconds: 10
        #  periodSeconds: 3
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP
