apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: video-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: video
    spec:
      containers:
      - image: docker.io/stashvala/streaming_app:videos-api
        imagePullPolicy: Always
        name: kubernetes-video
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: googlecloud
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-video:5432/video
          - name: KUMULUZEE_DATASOURCES0_PASSWORD
            value: postgres
        ports:
        - containerPort: 8081
          name: server
          protocol: TCP
