version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user
    ports:
      - "5432:5432"
  customer-service:
    image: users-api:1.00
    environment:
      - KUMULUZEE_DATASOURCES0_CONNECTIONURL=jdbc:postgresql://postgres:5432/user
    ports:
      - "8080:8080"
    depends_on:
      - postgres
